version: "3.7"


# Define the machines on its subnet
services:
  ## Server Subnet
  mailserver:
    image: ${REPOSITORY}:${MAILSERVER}
    container_name: ${MAILSERVER}
    restart: always
    network_mode: bridge
  fileserver:
    image: ${REPOSITORY}:${FILE}
    container_name: ${FILE}
    restart: always
    network_mode: bridge
  webserver:
    image: ${REPOSITORY}:${WEB}
    container_name: ${WEB}
    restart: always
    network_mode: bridge
  backupserver:
    image: ${REPOSITORY}:${BACKUP}
    container_name: ${BACKUP}
    restart: always
    network_mode: bridge


  ## Management Subnet
  Mclient1:
    image: ${REPOSITORY}:${LCLIENT}
    container_name: M${LCLIENT}1
    restart: always
    privileged: true
    depends_on: 
      - ${FILE}
      - ${MAILSERVER}
      - ${WEB}
      - ${BACKUP}
    network_mode: bridge
  ## Office Subnet
  Oclient1:
    image: ${REPOSITORY}:${LCLIENT}
    container_name: O${LCLIENT}1
    restart: always
    privileged: true
    depends_on: 
      - ${FILE}
      - ${MAILSERVER}
      - ${WEB}
      - ${BACKUP}
    network_mode: bridge
  ## Developer Subnet
  Dclient1:
    image: ${REPOSITORY}:${LCLIENT}
    container_name: D${LCLIENT}1
    restart: always
    privileged: true
    depends_on: 
      - ${FILE}
      - ${MAILSERVER}
      - ${WEB}
      - ${BACKUP}
    network_mode: bridge